// Homoglyph database: maps suspicious lookalike characters to their Latin equivalents
// Sources: Unicode confusables data + known AI watermarking techniques

export interface HomoglyphEntry {
  latin: string       // The expected Latin character
  script: string      // Source script name
  unicodeName: string // Unicode character name
}

// Map from suspicious codepoint → Latin equivalent info
export const HOMOGLYPH_MAP: Map<number, HomoglyphEntry> = new Map([
  // Cyrillic lookalikes (most common in AI watermarking)
  [0x0430, { latin: 'a', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER A' }],
  [0x0410, { latin: 'A', script: 'Cyrillic', unicodeName: 'CYRILLIC CAPITAL LETTER A' }],
  [0x0432, { latin: 'B', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER VE' }],
  [0x0412, { latin: 'B', script: 'Cyrillic', unicodeName: 'CYRILLIC CAPITAL LETTER VE' }],
  [0x0441, { latin: 'c', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER ES' }],
  [0x0421, { latin: 'C', script: 'Cyrillic', unicodeName: 'CYRILLIC CAPITAL LETTER ES' }],
  [0x0435, { latin: 'e', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER IE' }],
  [0x0415, { latin: 'E', script: 'Cyrillic', unicodeName: 'CYRILLIC CAPITAL LETTER IE' }],
  [0x0455, { latin: 'S', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER DZE' }],
  [0x0456, { latin: 'i', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I' }],
  [0x0406, { latin: 'I', script: 'Cyrillic', unicodeName: 'CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I' }],
  [0x0458, { latin: 'j', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER JE' }],
  [0x04cf, { latin: 'l', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER PALOCHKA' }],
  [0x04c0, { latin: 'I', script: 'Cyrillic', unicodeName: 'CYRILLIC LETTER PALOCHKA' }],
  [0x043e, { latin: 'o', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER O' }],
  [0x041e, { latin: 'O', script: 'Cyrillic', unicodeName: 'CYRILLIC CAPITAL LETTER O' }],
  [0x0440, { latin: 'p', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER ER' }],
  [0x0420, { latin: 'P', script: 'Cyrillic', unicodeName: 'CYRILLIC CAPITAL LETTER ER' }],
  [0x0445, { latin: 'x', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER HA' }],
  [0x0425, { latin: 'X', script: 'Cyrillic', unicodeName: 'CYRILLIC CAPITAL LETTER HA' }],
  [0x0443, { latin: 'y', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER U' }],
  [0x0423, { latin: 'Y', script: 'Cyrillic', unicodeName: 'CYRILLIC CAPITAL LETTER U' }],
  [0x04ae, { latin: 'Y', script: 'Cyrillic', unicodeName: 'CYRILLIC CAPITAL LETTER STRAIGHT U' }],
  [0x04af, { latin: 'y', script: 'Cyrillic', unicodeName: 'CYRILLIC SMALL LETTER STRAIGHT U' }],

  // Greek lookalikes
  [0x03b1, { latin: 'a', script: 'Greek', unicodeName: 'GREEK SMALL LETTER ALPHA' }],
  [0x0391, { latin: 'A', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER ALPHA' }],
  [0x03b2, { latin: 'B', script: 'Greek', unicodeName: 'GREEK SMALL LETTER BETA' }],
  [0x0392, { latin: 'B', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER BETA' }],
  [0x03b5, { latin: 'e', script: 'Greek', unicodeName: 'GREEK SMALL LETTER EPSILON' }],
  [0x0395, { latin: 'E', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER EPSILON' }],
  [0x03b7, { latin: 'n', script: 'Greek', unicodeName: 'GREEK SMALL LETTER ETA' }],
  [0x0397, { latin: 'H', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER ETA' }],
  [0x03b9, { latin: 'i', script: 'Greek', unicodeName: 'GREEK SMALL LETTER IOTA' }],
  [0x0399, { latin: 'I', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER IOTA' }],
  [0x03ba, { latin: 'k', script: 'Greek', unicodeName: 'GREEK SMALL LETTER KAPPA' }],
  [0x039a, { latin: 'K', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER KAPPA' }],
  [0x03bd, { latin: 'v', script: 'Greek', unicodeName: 'GREEK SMALL LETTER NU' }],
  [0x039d, { latin: 'N', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER NU' }],
  [0x03bf, { latin: 'o', script: 'Greek', unicodeName: 'GREEK SMALL LETTER OMICRON' }],
  [0x039f, { latin: 'O', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER OMICRON' }],
  [0x03c1, { latin: 'p', script: 'Greek', unicodeName: 'GREEK SMALL LETTER RHO' }],
  [0x03a1, { latin: 'P', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER RHO' }],
  [0x03c3, { latin: 'o', script: 'Greek', unicodeName: 'GREEK SMALL LETTER SIGMA' }],
  [0x03c4, { latin: 't', script: 'Greek', unicodeName: 'GREEK SMALL LETTER TAU' }],
  [0x03c5, { latin: 'u', script: 'Greek', unicodeName: 'GREEK SMALL LETTER UPSILON' }],
  [0x03c7, { latin: 'x', script: 'Greek', unicodeName: 'GREEK SMALL LETTER CHI' }],
  [0x03a7, { latin: 'X', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER CHI' }],
  [0x03c9, { latin: 'w', script: 'Greek', unicodeName: 'GREEK SMALL LETTER OMEGA' }],
  [0x03a9, { latin: 'W', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER OMEGA' }],
  [0x03a4, { latin: 'T', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER TAU' }],
  [0x03a5, { latin: 'Y', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER UPSILON' }],
  [0x0396, { latin: 'Z', script: 'Greek', unicodeName: 'GREEK CAPITAL LETTER ZETA' }],

  // Armenian lookalikes
  [0x0555, { latin: 'S', script: 'Armenian', unicodeName: 'ARMENIAN CAPITAL LETTER OH' }],
  [0x0578, { latin: 'n', script: 'Armenian', unicodeName: 'ARMENIAN SMALL LETTER VO' }],
  [0x057d, { latin: 'u', script: 'Armenian', unicodeName: 'ARMENIAN SMALL LETTER SEH' }],
  [0x0580, { latin: 'p', script: 'Armenian', unicodeName: 'ARMENIAN SMALL LETTER REH' }],
  [0x0581, { latin: 'd', script: 'Armenian', unicodeName: 'ARMENIAN SMALL LETTER CO' }],

  // Latin Extended lookalikes (Mathematical, Letterlike)
  [0x0261, { latin: 'g', script: 'Latin Extended', unicodeName: 'LATIN SMALL LETTER SCRIPT G' }],
  [0x1d00, { latin: 'A', script: 'Phonetic Ext', unicodeName: 'LATIN LETTER SMALL CAPITAL A' }],
  [0x1d0c, { latin: 'L', script: 'Phonetic Ext', unicodeName: 'LATIN LETTER SMALL CAPITAL L WITH STROKE' }],
  [0x1d18, { latin: 'P', script: 'Phonetic Ext', unicodeName: 'LATIN LETTER SMALL CAPITAL P' }],

  // Mathematical Alphanumeric Symbols (U+1D400–U+1D7FF)
  [0x1d41a, { latin: 'a', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL A' }],
  [0x1d41b, { latin: 'b', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL B' }],
  [0x1d41c, { latin: 'c', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL C' }],
  [0x1d41d, { latin: 'd', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL D' }],
  [0x1d41e, { latin: 'e', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL E' }],
  [0x1d41f, { latin: 'f', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL F' }],
  [0x1d420, { latin: 'g', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL G' }],
  [0x1d421, { latin: 'h', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL H' }],
  [0x1d422, { latin: 'i', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL I' }],
  [0x1d423, { latin: 'j', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL J' }],
  [0x1d424, { latin: 'k', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL K' }],
  [0x1d425, { latin: 'l', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL L' }],
  [0x1d426, { latin: 'm', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL M' }],
  [0x1d427, { latin: 'n', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL N' }],
  [0x1d428, { latin: 'o', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL O' }],
  [0x1d429, { latin: 'p', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL P' }],
  [0x1d42a, { latin: 'q', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL Q' }],
  [0x1d42b, { latin: 'r', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL R' }],
  [0x1d42c, { latin: 's', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL S' }],
  [0x1d42d, { latin: 't', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL T' }],
  [0x1d42e, { latin: 'u', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL U' }],
  [0x1d42f, { latin: 'v', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL V' }],
  [0x1d430, { latin: 'w', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL W' }],
  [0x1d431, { latin: 'x', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL X' }],
  [0x1d432, { latin: 'y', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL Y' }],
  [0x1d433, { latin: 'z', script: 'Math', unicodeName: 'MATHEMATICAL BOLD SMALL Z' }],

  // Fullwidth Latin (U+FF01–U+FF5E)
  [0xff41, { latin: 'a', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER A' }],
  [0xff42, { latin: 'b', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER B' }],
  [0xff43, { latin: 'c', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER C' }],
  [0xff44, { latin: 'd', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER D' }],
  [0xff45, { latin: 'e', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER E' }],
  [0xff46, { latin: 'f', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER F' }],
  [0xff47, { latin: 'g', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER G' }],
  [0xff48, { latin: 'h', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER H' }],
  [0xff49, { latin: 'i', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER I' }],
  [0xff4a, { latin: 'j', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER J' }],
  [0xff4b, { latin: 'k', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER K' }],
  [0xff4c, { latin: 'l', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER L' }],
  [0xff4d, { latin: 'm', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER M' }],
  [0xff4e, { latin: 'n', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER N' }],
  [0xff4f, { latin: 'o', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER O' }],
  [0xff50, { latin: 'p', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER P' }],
  [0xff51, { latin: 'q', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER Q' }],
  [0xff52, { latin: 'r', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER R' }],
  [0xff53, { latin: 's', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER S' }],
  [0xff54, { latin: 't', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER T' }],
  [0xff55, { latin: 'u', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER U' }],
  [0xff56, { latin: 'v', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER V' }],
  [0xff57, { latin: 'w', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER W' }],
  [0xff58, { latin: 'x', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER X' }],
  [0xff59, { latin: 'y', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER Y' }],
  [0xff5a, { latin: 'z', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN SMALL LETTER Z' }],
  [0xff21, { latin: 'A', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER A' }],
  [0xff22, { latin: 'B', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER B' }],
  [0xff23, { latin: 'C', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER C' }],
  [0xff24, { latin: 'D', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER D' }],
  [0xff25, { latin: 'E', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER E' }],
  [0xff26, { latin: 'F', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER F' }],
  [0xff27, { latin: 'G', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER G' }],
  [0xff28, { latin: 'H', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER H' }],
  [0xff29, { latin: 'I', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER I' }],
  [0xff2a, { latin: 'J', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER J' }],
  [0xff2b, { latin: 'K', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER K' }],
  [0xff2c, { latin: 'L', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER L' }],
  [0xff2d, { latin: 'M', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER M' }],
  [0xff2e, { latin: 'N', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER N' }],
  [0xff2f, { latin: 'O', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER O' }],
  [0xff30, { latin: 'P', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER P' }],
  [0xff31, { latin: 'Q', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER Q' }],
  [0xff32, { latin: 'R', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER R' }],
  [0xff33, { latin: 'S', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER S' }],
  [0xff34, { latin: 'T', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER T' }],
  [0xff35, { latin: 'U', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER U' }],
  [0xff36, { latin: 'V', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER V' }],
  [0xff37, { latin: 'W', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER W' }],
  [0xff38, { latin: 'X', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER X' }],
  [0xff39, { latin: 'Y', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER Y' }],
  [0xff3a, { latin: 'Z', script: 'Fullwidth', unicodeName: 'FULLWIDTH LATIN CAPITAL LETTER Z' }],

  // Common symbol lookalikes (genuine cross-script confusion)
  [0x03f3, { latin: 'j', script: 'Greek', unicodeName: 'GREEK LETTER YOT' }],
  [0x037e, { latin: ';', script: 'Greek', unicodeName: 'GREEK QUESTION MARK' }],
  // NOTE: curly/typographic quotes (U+2018/2019/201C/201D) and dashes
  // (U+2013/2014/2212) are intentionally NOT listed here — they are
  // legitimate typographic punctuation handled by the TYPO_PUNCT category.
])
